home/urls.py
from django.urls import path
from home import views
app_name = 'home'
urlpatterns=[
    path("home/",views.ViewHome,name="view_home"),
    path("about/",views.About,name='about'),
    path('',views.redirect_home,name='redirect_home')
]

my_pokemon_wiki/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trainers/', include('trainers.urls')),
    path('', include('home.urls')),
    path('wiki/',include('wiki.urls')),
]

trainers/urls.py
from django.urls import path
from trainers import views


app_name = 'trainers'
urlpatterns=[
    path("register/",views.TrainerRegister,name="trainer_register"),
    path("login/",views.TrainerLogin,name="trainer_login"),
    path('logout/', views.LogoutTrainer, name='logout_trainer'),
    path('change_password/', views.change_password, name='change_password'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pokemon - One of worlds biggest franchises</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">MahanMirabdi &copy; Pokemon wiki 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
  <div class="container px-5">
      <a class="navbar-brand" href="{% url 'home:view_home' %}">Pokemon wiki</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'trainers:logout_trainer' %}">Logout</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'trainers:change_password' %}">change password</a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'trainers:trainer_register' %}">Sign Up</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'trainers:trainer_login' %}">Log In</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" href="{% url 'home:about' %}">About Us</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'pokemon_list' %}">Wiki</a></li>
              {% if user.is_authenticated %}
                <span class="nav-link fw-bold text-primary bg-secondary text-white">Welcome, {{ user.username }}!</span>
              {% endif %}
          </ul>
      </div>
  </div>
</nav>